---
title: "Project Draft"
author: "Luke Fredrickson"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import}

library(tidyverse)
library(ggmap)

properties <- read.csv("properties.csv")



```

## Including Plots

You can also embed plots, for example:

```{r num_properties}

NumProperties <- properties %>% group_by(Owner) %>% summarize(nProperties = n())

summary(NumProperties$nProperties)

ggplot(data = NumProperties, 
       mapping = aes(nProperties)) + geom_bar()

ggplot(data = NumProperties %>% filter(nProperties >= 5), 
       mapping = aes(nProperties)) + geom_bar()

```



```{r rental_types}

ggplot(data = properties %>% filter(!is.na(LandUseCode)), 
       mapping = aes(LandUseCode)) + geom_bar()

```



```{r CoC_type}

ggplot(data = properties %>% filter(!is.na(CoCYears)), 
       mapping = aes(CoCYears)) + geom_bar()

```



```{r value_vs_coc}

ggplot(data = properties %>% filter(!is.na(CoCYears) & CoCYears != 0 & !is.na(LastMhInspectionDate) & PropertyValue < 1000000), 
       mapping = aes(x=factor(CoCYears), y=PropertyValue)) + geom_boxplot()

```